from PyQt5 import QtCore, QtGui, QtWidgets
class Auth_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(473, 503)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("color: rgb(102, 198, 200)")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-1, -1, 571, 501))
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setObjectName("stackedWidget")

        # login page ui code
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.loginFrame = QtWidgets.QFrame(self.loginPage)
        self.loginFrame.setEnabled(True)
        self.loginFrame.setGeometry(QtCore.QRect(10, 10, 451, 441))
        self.loginFrame.setAcceptDrops(False)
        self.loginFrame.setAutoFillBackground(True)
        self.loginFrame.setStyleSheet("color:rgb(74, 74, 74)")
        self.loginFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.loginFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginFrame.setLineWidth(2)
        self.loginFrame.setObjectName("loginFrame")
        self.usernameInput = QtWidgets.QLineEdit(self.loginFrame)
        self.usernameInput.setGeometry(QtCore.QRect(130, 30, 311, 31))
        self.usernameInput.setObjectName("usernameInput")
        self.usernamelabel = QtWidgets.QLabel(self.loginFrame)
        self.usernamelabel.setGeometry(QtCore.QRect(20, 30, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.usernamelabel.setFont(font)
        self.usernamelabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.usernamelabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.usernamelabel.setObjectName("usernamelabel")
        self.pwdInput = QtWidgets.QLineEdit(self.loginFrame)
        self.pwdInput.setGeometry(QtCore.QRect(130, 80, 311, 31))
        self.pwdInput.setObjectName("pwdInput")
        self.pwdInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwdlabel = QtWidgets.QLabel(self.loginFrame)
        self.pwdlabel.setGeometry(QtCore.QRect(20, 80, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.pwdlabel.setFont(font)
        self.pwdlabel.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.pwdlabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pwdlabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pwdlabel.setObjectName("pwdlabel")
        self.loginButton = QtWidgets.QPushButton(self.loginFrame,)
        self.loginButton.setGeometry(QtCore.QRect(160, 210, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.loginButton.setFont(font)
        self.loginButton.setObjectName("loginButton")
        self.linkSignup = QtWidgets.QCommandLinkButton(self.loginFrame)
        self.linkSignup.setGeometry(QtCore.QRect(270, 380, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        self.linkSignup.setFont(font)
        self.linkSignup.setObjectName("linkSignup")
        self.label = QtWidgets.QLabel(self.loginFrame)
        self.label.setGeometry(QtCore.QRect(50, 390, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.remeberMe = QtWidgets.QCheckBox(self.loginFrame)
        self.remeberMe.setGeometry(QtCore.QRect(330, 149, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.remeberMe.setFont(font)
        self.remeberMe.setObjectName("remeberMe")
        self.stackedWidget.addWidget(self.loginPage)
        #--------------------------------------------------------------------------
        
        # signup page ui code
        self.signupPage = QtWidgets.QWidget()
        self.signupPage.setObjectName("signupPage")
        self.signupFrame = QtWidgets.QFrame(self.signupPage)
        self.signupFrame.setEnabled(True)
        self.signupFrame.setGeometry(QtCore.QRect(10, 10, 451, 441))
        self.signupFrame.setAcceptDrops(False)
        self.signupFrame.setAutoFillBackground(True)
        self.signupFrame.setStyleSheet("color:rgb(74, 74, 74)")
        self.signupFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.signupFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.signupFrame.setLineWidth(2)
        self.signupFrame.setObjectName("signupFrame")
        self.usernameInput_2 = QtWidgets.QLineEdit(self.signupFrame)
        self.usernameInput_2.setGeometry(QtCore.QRect(130, 30, 311, 31))
        self.usernameInput_2.setObjectName("usernameInput_2")
        self.usernamelabel_2 = QtWidgets.QLabel(self.signupFrame)
        self.usernamelabel_2.setGeometry(QtCore.QRect(20, 30, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.usernamelabel_2.setFont(font)
        self.usernamelabel_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.usernamelabel_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.usernamelabel_2.setObjectName("usernamelabel_2")
        self.pwdInput_2 = QtWidgets.QLineEdit(self.signupFrame)
        self.pwdInput_2.setGeometry(QtCore.QRect(130, 80, 311, 31))
        self.pwdInput_2.setObjectName("pwdInput_2")
        self.pwdInput_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwdlabel_2 = QtWidgets.QLabel(self.signupFrame)
        self.pwdlabel_2.setGeometry(QtCore.QRect(20, 80, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.pwdlabel_2.setFont(font)
        self.pwdlabel_2.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.pwdlabel_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pwdlabel_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pwdlabel_2.setObjectName("pwdlabel_2")
        self.signupButton = QtWidgets.QPushButton(self.signupFrame)
        self.signupButton.setGeometry(QtCore.QRect(160, 280, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.signupButton.setFont(font)
        self.signupButton.setObjectName("signupButton")
        self.pwdconfirmInput = QtWidgets.QLineEdit(self.signupFrame)
        self.pwdconfirmInput.setGeometry(QtCore.QRect(130, 150, 311, 31))
        self.pwdconfirmInput.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.pwdconfirmInput.setReadOnly(False)
        self.pwdconfirmInput.setObjectName("pwdconfirmInput")
        self.pwdconfirmInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwdconfirmlabel = QtWidgets.QLabel(self.signupFrame)
        self.pwdconfirmlabel.setEnabled(True)
        self.pwdconfirmlabel.setGeometry(QtCore.QRect(20, 120, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.pwdconfirmlabel.setFont(font)
        self.pwdconfirmlabel.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.pwdconfirmlabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pwdconfirmlabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pwdconfirmlabel.setWordWrap(True)
        self.pwdconfirmlabel.setObjectName("pwdconfirmlabel")
        self.linkLogin = QtWidgets.QCommandLinkButton(self.signupFrame)
        self.linkLogin.setGeometry(QtCore.QRect(270, 380, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        self.linkLogin.setFont(font)
        self.linkLogin.setObjectName("linkLogin")
        self.label_2 = QtWidgets.QLabel(self.signupFrame)
        self.label_2.setGeometry(QtCore.QRect(50, 390, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.signupPage)
        # ----------------------------------------------------------------------

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 473, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SignUp/Login"))
        self.usernamelabel.setText(_translate("MainWindow", "UserName:"))
        self.pwdlabel.setText(_translate("MainWindow", "Password:"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.linkSignup.setText(_translate("MainWindow", "Sign Up!"))
        self.label.setText(_translate("MainWindow", "Don't have an account!"))
        self.remeberMe.setText(_translate("MainWindow", "Remember Me"))
        self.usernamelabel_2.setText(_translate("MainWindow", "UserName:"))
        self.pwdlabel_2.setText(_translate("MainWindow", "Password:"))
        self.signupButton.setText(_translate("MainWindow", "Sign Up"))
        self.pwdconfirmlabel.setText(_translate("MainWindow", "Retype Password:"))
        self.linkLogin.setText(_translate("MainWindow", "Login!"))
        self.label_2.setText(_translate("MainWindow", "Already have an account!"))


